name: Continuous Integration

on:
  push:
  pull_request:
    branches:
      - main
      - develop
  workflow_call:

jobs:
  ci:
    name: CI ( ${{ matrix.node-version }} on ${{ matrix.os}} )
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [14.x, 16.x]
        os: [ubuntu-20.04, windows-2022, macos-11]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test

