name: Release

on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*-beta.*'
      - 'v*.*.*-nightly.*'

jobs:
  release:
    needs: [release-npm]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Download binary
        uses: actions/download-artifact@v3
        with:
          name: binaries
          path: ./release
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: ${{ contains(github.ref, '-beta') || contains(github.ref, '-nightly')}}
          files: ./release/*

  release-npm:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'
      - run: yarn install
      - name: Publish to npm
        run: yarn publish
        env:
          NPM_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
