name: Release

on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*-beta.*'
      - 'v*.*.*-nightly.*'

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  release:
    needs: [ci]
    runs-on: ubuntu-20.04
    env:
      GITHUB_PRERELEASE: ${{ contains(github.ref, '-beta') || contains(github.ref, '-nightly') || contains(github.ref, '-canary') }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Publish to npm
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: get previous version
        run: |

      - name: make tarball
        run: npx oclif pack tarballs
      - name: Upload tarball
        uses: softprops/action-gh-release@v1
        with:
          files: ./dist/global-git-clone-*
          prerelease: ${{ env.GITHUB_PRERELEASE }}
          body_path: ./CHANGELOG.md



