name: Release

on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*-beta.*'
      - 'v*.*.*-nightly.*'

jobs:
  release:
    needs: [release-npm, release-binary]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Download binary
        uses: actions/download-artifact@v3
        with:
          name: binaries
          path: ./release
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: ${{ contains(github.ref, '-beta') || contains(github.ref, '-nightly')}}
          files: ./release/*

  release-npm:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'
      - run: yarn install
      - name: Publish to npm
        run: yarn publish
        env:
          NPM_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  release-binary:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'
      - run: yarn install
      - run: yarn build
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: amd64,arm64
      - name: Build binaries
        run: yarn package
      - name: upload binaries
        id: upload-binaries
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: ./release
